goal_topic: /move_base_simple/goal
is_reached_goal_topic: waypoint/is_reached
regist_goal_pose_topic: waypoint/regist_pose
regist_goal_point_topic: waypoint/regist_point
visualize_waypoints_topic: waypoints
robot_base_frame: base_link
global_frame: map
goal_publish_frequency: 0.5
goal_check_frequency: 1.0
default_goal_radius: 1.0
# waypoints_file: $(find waypoint_server)/config/waypoints/20220625_tsuda_ch.yaml
waypoints_file: $(find waypoint_server)/config/waypoints/tsudanuma.yaml
#waypoints_file: $(find waypoint_server)/config/waypoints/open_campus.yaml
#route_file: $(find waypoint_server)/config/routes/20220625_tsuda_ch.yaml
# route_file: $(find waypoint_server)/config/routes/open_campus.yaml
route_file: $(find waypoint_server)/config/routes/tsudanuma.yaml
enable_loop: true
debug: false
